apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cronjob.yaml
configMapGenerator:
  - name: morning-digest-feeds
    files:
      - feeds.yaml
generatorOptions:
  disableNameSuffixHash: true
